import "@/lib/db.js"
import { Provider } from  "@/app/provider";
import HeaderAdmin from "@/components/layout/HeaderAdmin";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
    return (
        <Provider>
            <HeaderAdmin />
            {children}
        </Provider>
    )
}
